language: node_js
node_js:
  - stable
before_script: chmod 0777 ./node_modules/.bin/mocha
branches:
  only:
  - development
  notifications:
    email:
      recipients:
        - conormcbride158@gmail.com      # uae your own
        - other@example.com    # uae other (optional)
      on_success: never        # default: change
      on_failure: always       # default: always