language: node_js
node_js:
  - stable
script:
    - npm run coverage
after_success:
    - npm run report-coverage
branches:
 only:
 - workingbranch

notifications:
  email:
    recipients:
     - conormcbride158@gmail.com      # uae your own

    on_success: never        # default: change
    on_failure: always       # default: always